SiteWeb/Areas/Admin/Controllers/FrontMenuController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TZGCMS.SiteWeb.Filters;
using TZGCMS.Data.Entity.Identity;
using TZGCMS.Data.Entity.PageMetas;
using TZGCMS.Data.Enums;
using TZGCMS.Infrastructure.Configs;
using TZGCMS.Infrastructure.Helper;
using TZGCMS.Model.Admin.InputModel.Menus;
using TZGCMS.Model.Admin.ViewModel;
using TZGCMS.Model.Admin.ViewModel.Menus;
using TZGCMS.Resources.Admin;
using TZGCMS.Service.Identity;
using TZGCMS.Service.PageMetas;
using QNZ.Data;
using TZGCMS.Model;
using Menu = TZGCMS.Data.Entity.Identity.Menu;
using System.Data.Entity;
using TZGCMS.Infrastructure.Extensions;
using System.Threading.Tasks;

namespace TZGCMS.SiteWeb.Areas.Admin.Controllers
{
    [SIGAuth]
    public class FrontMenuController : QNZBaseController
    {
        // GET: Admin/FrontMenu
        private readonly IMenuCategoryServices _menuCategoryService;
        private readonly IMenuServices _menuService;
        private readonly IPageMetaServices _pageMetaService;
        private readonly IMapper _mapper;
        private IQNZDbContext _db;

        public FrontMenuController(IMenuCategoryServices menuCategoryService, IMenuServices menuService, IPageMetaServices pageMetaService, IMapper mapper, IQNZDbContext db)
        {
            _menuService = menuService;
            _menuCategoryService = menuCategoryService;
            _pageMetaService = pageMetaService;
            _mapper = mapper;
            _db = db;
        }
        //
        // GET: /Admin/Menu/ 
        public ActionResult Index()
        {
            IEnumerable<QNZ.Data.MenuCategory> menuCategories = _db.MenuCategories.Where(m=>m.Id!= SettingsManager.Menu.BackMenuCId);
            return View(menuCategories);
        }



        [HttpGet]
        public ActionResult AddCategory()
        {
            var vCategory = new MenuCategoryIM
            {
                Active = true,
                Importance = 0
            };

            return PartialView("_AddCategory", vCategory);
        }

        [HttpPost]
        public JsonResult AddCategory(MenuCategoryIM vm)
        {

            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            var newCategory = _mapper.Map<MenuCategoryIM, Data.Entity.Identity.MenuCategory>(vm);

            _menuCategoryService.Create(newCategory);



            IEnumerable<Data.Entity.Identity.MenuCategory> menuCategories = _menuCategoryService.GetAll().Where(m => m.Id != SettingsManager.Menu.BackMenuCId);
        
            AR.Data = RenderPartialViewToString("_CategoryList", menuCategories);

            AR.SetSuccess(String.Format(Messages.AlertCreateSuccess, EntityNames.MenuCategory));
            return Json(AR, JsonRequestBehavior.DenyGet);

        }




        [HttpGet]
        public ActionResult EditCategory(int id)
        {

            var category = _menuCategoryService.GetById(id);
            if (category == null)
            {
                AR.Setfailure(Messages.HttpNotFound);
                return Json(AR, JsonRequestBehavior.AllowGet);
            }

            var vm = _mapper.Map<MenuCategoryIM>(category);

            return PartialView("_EditCategory", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult EditCategory(MenuCategoryIM vm)
        {

            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            var newCategory = _mapper.Map<MenuCategoryIM, Data.Entity.Identity.MenuCategory>(vm);

            _menuCategoryService.Update(newCategory);


            var menuCategories = _menuCategoryService.GetAll().Where(m => m.Id != SettingsManager.Menu.BackMenuCId);

            AR.Data = RenderPartialViewToString("_CategoryList", menuCategories);

            AR.SetSuccess(String.Format(Messages.AlertUpdateSuccess, EntityNames.MenuCategory));
            return Json(AR, JsonRequestBehavior.DenyGet);

        }


        // DELETE: /User/DeleteSite
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteCategory(int id)
        {

            var vCategory = _menuCategoryService.GetById(id);
            if (vCategory.IsSys)
            {
                AR.Setfailure("系统内置栏目，不能删除！");
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            //if (vCategory.Menus.Any())
            //{
            //    AR.Setfailure("此分类下面还有文章存在，不能删除！");
            //    return Json(AR, JsonRequestBehavior.DenyGet);
            //}

            var menuCategories = _menuCategoryService.GetAll().Where(m => m.Id != SettingsManager.Menu.BackMenuCId);
            AR.Data = RenderPartialViewToString("_CategoryList", menuCategories);

            _menuCategoryService.Delete(vCategory);
            AR.SetSuccess(String.Format(Messages.AlertDeleteSuccess, EntityNames.MenuCategory));
            return Json(AR, JsonRequestBehavior.DenyGet);

        }




        /// <summary>
        /// 获取单组菜单
        /// </summary>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult GetMenus(int categoryId)
        {
            // var menus = _menuService.GetLevelMenusByCategoryId(categoryId);
            var menus =  _db.Menus.Where(d => d.CategoryId == categoryId).OrderBy(d => d.Importance).ToList();
            return PartialView("_MenuList", menus);
        }





        //[HttpGet]
        //public ActionResult CreateMenu(int categoryId, int? parentId)
        //{
        //    var vMenu = new Menu();
        //    FrontMenuIM newDto = _mapper.Map<FrontMenuIM>(vMenu);

        //    newDto.CategoryId = (int)categoryId;
        //    newDto.ParentId = parentId??null;
        //    return PartialView("_MenuCreate", newDto);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<JsonResult> CreateMenu(FrontMenuIM vm)
        {

            if (ModelState.IsValid)
            {
                vm.Url = vm.Url.ToLower();
                var vMenu = _mapper.Map<Data.Entity.Identity.Menu>(vm);
                if (vm.ParentId != null)
                {
                    var parentMenu = _menuService.GetById(vMenu.ParentId.Value);
                    vMenu.LayoutLevel = parentMenu.LayoutLevel + 1;
                }
                else
                {
                    vMenu.LayoutLevel = 0;
                }
                //vMenu.CreatedDate = DateTime.Now;
                //vMenu.CreatedBy = Site.CurrentUserName;

                _menuService.Create(vMenu);
                _menuService.ResetSort((vMenu.CategoryId));

                await SetPageMetaAsync(_db, (short)ModelType.ARTICLECATEGORY, vm.Url, vm.Title, vm.SEOTitle, vm.Keywords, vm.SEODescription);
               

                var menus = _menuService.GetMenusByCategoryId(vMenu.CategoryId);
                AR.Id = vm.CategoryId;
                AR.Data = RenderPartialViewToString("_MenuList", menus);

                AR.SetSuccess("已成功新增菜单");
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            AR.Setfailure("编辑菜单失败");
            return Json(AR, JsonRequestBehavior.DenyGet);

            //   return RedirectToAction("Index");

        }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult EditMenu(int categoryId, int? parentId, int? id)
        {

            if (id > 0)
            {
                var vMenu = _db.Menus.Find(id);
                FrontMenuIM dto = _mapper.Map<FrontMenuIM>(vMenu);

                if (!string.IsNullOrEmpty(dto.Url))
                {
                    var pageMeta = _db.PageMetas.FirstOrDefault(d=>d.ModelType == (short)ModelType.MENU && d.ObjectId == dto.Url);
                    if (pageMeta != null)
                    {
                        dto.SEOTitle = pageMeta.Title;
                        dto.Keywords = pageMeta.Keyword;
                        dto.SEODescription = pageMeta.Description;
                    }
                }
                return PartialView("_MenuEdit", dto);
            }
            else
            {
               
                FrontMenuIM newDto = new FrontMenuIM {
                    CategoryId = categoryId,
                    ParentId = parentId
                };

                return PartialView("_MenuEdit", newDto);
            }

        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<JsonResult> EditMenu(FrontMenuIM vm)
        {
            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }
            vm.Url = vm.Url.ToLower();
            if (vm.Id > 0)
            {
                var orgMenu = await _db.Menus.FindAsync(vm.Id);
                var pageMeta = await _db.PageMetas.FirstOrDefaultAsync(d => d.ModelType == (short)ModelType.MENU && d.ObjectId == orgMenu.Url);

                orgMenu = _mapper.Map(vm, orgMenu);
                orgMenu.UpdatedDate = DateTime.Now;
                orgMenu.UpdatedBy = Site.CurrentUserName;

                _db.Entry(orgMenu).State = EntityState.Modified;



                //orgMenu.Title = vMenu.Title;
                //orgMenu.MenuType = vMenu.MenuType;
                //orgMenu.Active = vMenu.Active;
                //orgMenu.Action = vMenu.Action;
                //orgMenu.Area = vMenu.Area;
                //orgMenu.CategoryId = vMenu.CategoryId;
                //orgMenu.Controller = vMenu.Controller;
                //orgMenu.Iconfont = vMenu.Iconfont;
                //orgMenu.ParentId = vMenu.ParentId;

SiteWeb/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TZGCMS.Infrastructure.Cache;
using TZGCMS.Infrastructure.Configs;
using QNZ.Data;
using System.Data.Entity;

namespace TZGCMS.SiteWeb.Controllers
{

    public class MenuController : Controller
    {
        private readonly IQNZDbContext _db;
        private readonly ICacheService _cacheService;
        public MenuController(ICacheService cacheService, IQNZDbContext db)
        {
            _cacheService = cacheService;
            _db = db;
        }


        public PartialViewResult SiteNav(int cid)
        {
            var vm = new List<Menu>();

            string key = "Menus_Active_Category_" + cid.ToString();
            if (SettingsManager.Site.EnableCaching)
            {
                if (_cacheService.IsSet(key))
                {
                    vm = (List<Menu>)_cacheService.Get(key);

                }
                else
                {
                    vm = _db.Menus.Include(d => d.Menus).AsNoTracking().Where(m => m.Active && m.CategoryId == cid)
                    .OrderBy(d => d.Importance).ToList();

                    _cacheService.Set(key, vm, SettingsManager.Site.CacheDuration);
                }
            }
            else
            {
                vm = _db.Menus.Include(d => d.Menus).AsNoTracking().Where(m => m.Active && m.CategoryId == cid)
                  .OrderBy(d => d.Importance).ToList();
            }

            return PartialView("_SiteNav", vm);
        }
     
        public PartialViewResult SiteFooterNav(int cid)
        {
            var vm = new List<Menu>();
            string key = "Menus_Active_Category_" + cid.ToString();

            if (SettingsManager.Site.EnableCaching)
            {
                if (_cacheService.IsSet(key))
                {
                    vm = (List<Menu>)_cacheService.Get(key);

                }
                else
                {

                    vm = _db.Menus.Include(d => d.Menus).AsNoTracking().Where(m => m.Active && m.CategoryId == cid)
                  .OrderBy(d => d.Importance).ToList();
                    _cacheService.Set(key, vm, SettingsManager.Site.CacheDuration);
                }
            }
            else
            {
                vm = _db.Menus.Include(d => d.Menus).AsNoTracking().Where(m => m.Active && m.CategoryId == cid)
                    .OrderBy(d => d.Importance).ToList();
              
            }            
    
            return PartialView("_SiteFooterNav", vm);
        }
    }
}

SiteWeb/Areas/Admin/Views/FrontMenu/_AddCategory.cshtml
@model MenuCategoryIM

@using (Ajax.BeginForm("AddCategory", "FrontMenu",
                new AjaxOptions()
                {
                    HttpMethod = "POST",
                    OnBegin = "onBeginSave",
                    OnComplete = "onCompleteSave",
                    OnSuccess = "updateSuccess",
                    //OnFailure = "handleError",
                    //  UpdateTargetId = "RoleList"

                }, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <!-- 添加菜单 Modal -->
    <div class="modal fade" id="ModalMenuForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@string.Format("创建{0}", EntityNames.MenuCategory)</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Labels.Title })
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.Importance, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Importance, new { @class = "form-control", type = "number", placeholder = Labels.Importance })
                            @Html.ValidationMessageFor(model => model.Importance)
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-5 col-md-offset-2">
                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(model => model.Active)  @Html.DisplayNameFor(model => model.Active)
                                </label>
                            </div>
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Active)
                        </div>
                    </div>




                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save fa-fw"></i>保存</button>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

SiteWeb/Areas/Admin/Views/FrontMenu/_CategoryList.cshtml
@model IEnumerable<QNZ.Data.MenuCategory>
@foreach (var item in Model)
{

    <div class="col-sm-4 item-container">
        <div class="card">
            <header class="card-header">
                <div class="row align-items-center">
                    <div class="col">
                        <i class="iconfont icon-antdesign"></i> @item.Title
                    </div>
                    <div class="col-auto">
                        @Ajax.RawActionLink("<i class='iconfont icon-plus'></i>",
                      "EditMenu", "FrontMenu",
                      new { categoryId = item.Id },
                      new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "edit-container", OnComplete = "onAjaxComplete", OnSuccess = "OnSuccessLink" },
                      new { @class = "btn btn-primary btn-sm", title = Buttons.Add })

                        @Ajax.RawActionLink("<i class='iconfont icon-edit'></i>",
                            "EditCategory", "FrontMenu",
                            new { id = item.Id },
                            new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "edit-container", OnComplete = "onAjaxComplete", OnSuccess = "OnSuccessLink" },
                            new { @class = "btn btn-primary btn-sm", title = Buttons.Edit })

                        <a href="#" data-url="@Url.Action("DeleteCategory", new {id = item.Id})" class="btn btn-danger btn-sm delete-item" title="@Buttons.Delete">
                            <i class="iconfont icon-delete"></i>
                        </a>

                        <button type="button" class="btn btn-info btn-sm btn-refresh" data-id="@item.Id"
                                data-url="@Url.Action("resetSort",new { id=item.Id})">
                            <i class="iconfont icon-sort-ascending"></i>
                        </button>
                    </div>
                </div>
  
             
              
            </header>
            <section class="card-body" id="@string.Format("menu{0}",item.Id)">
                @Html.Action("GetMenus", new { categoryId = item.Id })
            </section>
            @*<footer class="card-footer">

            </footer>*@
        </div>
    </div>
}

SiteWeb/Areas/Admin/Views/FrontMenu/_EditCategory.cshtml
@model MenuCategoryIM

@using (Ajax.BeginForm("EditCategory", "FrontMenu",
                            new AjaxOptions()
                            {
                                HttpMethod = "POST",
                                OnBegin = "onBeginSave",
                                OnComplete = "onCompleteSave",
                                OnSuccess = "updateSuccess",
                                //OnFailure = "handleError",
                                //  UpdateTargetId = "RoleList"

                            }, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <!-- 添加菜单 Modal -->
    <div class="modal fade" id="ModalMenuForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">@string.Format("编辑{0}", EntityNames.MenuCategory)</h4>
                </div>
                <div class="modal-body">
                    
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Labels.Title })
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Importance, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Importance, new { @class = "form-control", type = "number", placeholder = Labels.Importance })

                            @Html.ValidationMessageFor(model => model.Importance)
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-5 col-md-offset-2">
                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(model => model.Active)  @Html.DisplayNameFor(model => model.Active)
                                </label>
                            </div>
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Active)
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save fa-fw"></i>保存</button>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

SiteWeb/Areas/Admin/Views/FrontMenu/_MenuEdit.cshtml
@model FrontMenuIM

@using (Ajax.BeginForm("EditMenu", "FrontMenu",
                            new AjaxOptions()
                            {
                                HttpMethod = "POST",
                                OnBegin = "onBeginSave",
                                OnComplete = "onCompleteSave",
                                OnSuccess = "onSuccess",
                                //UpdateTargetId =$"menu{Model.CategoryId}"

                            }, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


<!-- 添加菜单 Modal -->
<div class="modal fade" id="ModalMenuForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
               
                <h5 class="modal-title">创建菜单</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CategoryId)
                @Html.HiddenFor(model => model.ParentId)
                @Html.HiddenFor(model => model.Importance)
                <!-- Nav tabs -->
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" href="#product" aria-controls="product" role="tab" data-toggle="tab">@EntityNames.Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#seo" aria-controls="seo" role="tab" data-toggle="tab">SEO设置</a>
                    </li>
                </ul>



                <!-- Tab panes -->
                <div class="tab-content" style="padding-top:30px;">
                    <div role="tabpanel" class="tab-pane active" id="product">
                        <div class="form-group row">
                            @Html.LabelFor(model => model.Title, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Title)
                            </div>

                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.TitleEn, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.TitleEn, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TitleEn)
                            </div>

                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.MenuType, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.EnumDropDownListFor(model => model.MenuType, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MenuType)
                            </div>

                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.Url, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Url, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Url)
                            </div>

                        </div>


                        <div class="form-group row">
                            @Html.LabelFor(model => model.Iconfont, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                <div class="input-group">
                                    @Html.TextBoxFor(model => model.Iconfont, new { @class = "form-control", aria_describedby = "btnBackground" })

                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="btnBackground">浏览...</button>
                                    </div>
                                </div>
                                @Html.ValidationMessageFor(model => model.Iconfont)
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.Active, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                <div class="form-check" style="padding-left:0;">
                                    @Html.CheckBoxFor(model => model.Active)
                                    <label class="form-check-label" for="Active">
                                        [*控制菜单是否显示]
                                    </label>
                                </div>


                                @Html.ValidationMessageFor(model => model.Active)
                            </div>
                        </div>

                    </div>
                    <div role="tabpanel" class="tab-pane" id="seo">

                        <div class="form-group">
                            @Html.LabelFor(model => model.SEOTitle)

                            @Html.TextBoxFor(model => model.SEOTitle, new { @class = "form-control", placeholder = Labels.Title })
                            @Html.ValidationMessageFor(model => model.SEOTitle)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Keywords)

                            @Html.TextBoxFor(model => model.Keywords, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Keywords)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SEODescription)

                            @Html.TextAreaFor(model => model.SEODescription, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SEODescription)

                        </div>

                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save fa-fw"></i>保存</button>
            </div>
        </div>
    </div>
</div>
}

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

SiteWeb/Areas/Admin/Views/FrontMenu/_MoveMenu.cshtml
@model MoveFrontMenuVM

@helper ShowTree(IEnumerable<QNZ.Data.Menu> menus)
{
    <ul class="menuTree menuTreeRole list-unstyled">
        @foreach (var item in menus)
        {
            if (item.MenuType == (short)MenuType.PAGE || item.MenuType == (short)MenuType.NOLINK)
            {
                <li class="@(item.Menus.Any() ? "hasMenus" : "")">
                    <label class="@(item.Id==Model.Id ? "text-danger":"")">
                        <input type="radio" name="menuId" value="@item.Id" @(Model.CurrentParentId == item.Id ?"checked":"") @(item.Id==Model.Id ? "disabled" : "") />
                        @item.Title
                    </label>
                    @if (item.Menus.Any())
                    {
                        @ShowTree(item.Menus.OrderBy(c => c.Importance))
                    }
                </li>
            }

        }
    </ul>
}

@using (Ajax.BeginForm("MoveMenu", "Menu",
        new AjaxOptions()
        {
            HttpMethod = "POST",
            OnBegin = "onBeginSave",
            OnComplete = "onCompleteSave",
            OnSuccess = "onSuccess",
           // UpdateTargetId = $"menu{Model.CategoryId}"
           // OnFailure = "handleError",         

        }, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CurrentParentId)

    <!-- 添加菜单 Modal -->
    <div class="modal fade" id="ModalMenuForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">移动菜单</h4>
                </div>
                <div class="modal-body" style="height:450px;overflow-y:auto;padding-left:35px;">
                    @ShowTree(Model.Menus)
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save fa-fw"></i>保存</button>
                </div>
            </div>
        </div>
    </div>
}