SiteWeb/Controllers/ADController.cs
using QNZ.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TZGCMS.Infrastructure.Cache;
using TZGCMS.Service.Ads;

namespace TZGCMS.SiteWeb.Controllers
{
    public class ADController :Controller
    {

        private readonly IQNZDbContext _db;
        private readonly ICacheService _cacheService;
        public ADController(ICacheService cacheService, IQNZDbContext db)
        {
            _cacheService = cacheService;
            _db = db;
        }
        // GET: Carousel
        public PartialViewResult Carousels(string code)
        {
            var carousels = _db.CarouselSets.Where(d => d.Active && d.PositionSet.Code == code).OrderByDescending(d => d.ImageUrl).ToList();

            if (!carousels.Any())
            {
                TempData["Error"] = $"{code}广告位不存在！";
                return PartialView(null);
            }
            else
            {
                //var carousels = _carouselService.f(position.Id).OrderByDescending(m => m.Importance);
                ////var list = _mapper.Map<IEnumerable<Carousel>, IEnumerable<CarouselVM>>(position.Carousels.OrderByDescending(m => m.Importance));
                return PartialView(carousels);
            }
        }

        public PartialViewResult SingleAd(string code)
        {
            var carousel = _db.CarouselSets.OrderByDescending(d => d.ImageUrl).FirstOrDefault(d => d.Active && d.PositionSet.Code == code);

            if (carousel == null)
            {
                TempData["Error"] = $"{code}广告位不存在！";
                return PartialView(null);
            }
            else
            {              
                return PartialView(carousel);
            }
        }
        public PartialViewResult SingleAdForHome(string code)
        {
            var carousel = _db.CarouselSets.OrderByDescending(d => d.ImageUrl).FirstOrDefault(d => d.Active && d.PositionSet.Code == code);

            if (carousel == null)
            {
                TempData["Error"] = $"{code}广告位不存在！";
                return PartialView(null);
            }
            else
            {
                return PartialView(carousel);
            }
        }
    }
}

SiteWeb/Controllers/ContactController.cs
using AutoMapper.QueryableExtensions;
using QNZ.Data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TZGCMS.Data.Entity.Emails;
using TZGCMS.Data.Enums;
using TZGCMS.Infrastructure.Configs;
using TZGCMS.Infrastructure.Helper;
using TZGCMS.Model;
using TZGCMS.Model.Front.InputModel.Emails;
using TZGCMS.Model.Front.ViewModel;
using TZGCMS.Resources.Front;
using TZGCMS.Service.Emails;

namespace TZGCMS.SiteWeb.Controllers
{
    public class ContactController : BaseController
    {

        TZGCMS.Infrastructure.Email.IEmailService _emailService;
        private readonly IQNZDbContext _db;

        public ContactController(TZGCMS.Infrastructure.Email.IEmailService emailService, IQNZDbContext db)
        {
            _emailService = emailService;

            _db = db;
        }
        // GET: Contact
        public async Task<ActionResult> Index()
        {
            var vm = await _db.Outlets.Where(d => d.Active).OrderByDescending(d => d.Importance).ProjectTo<OutletVM>().ToListAsync();


            var url = Request.RawUrl;
            ViewBag.PageMeta = await _db.PageMetas.FirstOrDefaultAsync(d => d.ModelType == (short)ModelType.MENU && d.ObjectId == url);
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> SendEmail(EmailIM vm)
        {

            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            if (Session["SigCaptcha"] != null && Session["SigCaptcha"].ToString().ToLower() != vm.CaptchaText.ToLower())
            {
                ModelState.AddModelError(string.Empty, "验证码不正确!");
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
                // return View(model);
            }

            var template = await _db.EmailTemplateSets.FirstOrDefaultAsync(d => d.TemplateNo == "T003");
            // _templateService.GetEmailTemplateByTemplateNo("T003");
            if (template == null)
            {
                AR.Setfailure(string.Format(Messages.NoEmailTemplate, "T003"));
                return Json(AR, JsonRequestBehavior.DenyGet);
            }


            vm.Subject = SettingsManager.Site.SiteName + "联系邮件";
            var emailBody = ReplaceTemplate(template.Body);
            emailBody = emailBody.Replace("{Name}", vm.Name);
            emailBody = emailBody.Replace("{Phone}", vm.Phone);
            emailBody = emailBody.Replace("{Email}", vm.Email);
            emailBody = emailBody.Replace("{Message}", vm.Body);

            var emailAccount = await _db.EmailAccountSets.FindAsync(template.EmailAccountId);
            //_accountService.GetById(template.EmailAccountId);

            try
            {


                EmailSet email = new EmailSet
                {
                    Body = emailBody,
                    Subject = vm.Subject,
                    MailTo = vm.Email,
                    MailCc = string.Empty,
                    Active = true,
                    CreatedBy = vm.Name,
                    CreatedDate = DateTime.Now
                };

                _db.EmailSets.Add(email);
                await _db.SaveChangesAsync();
                // _emailListService.Create(email);

                _emailService.SendMail(vm.Name, vm.Email, SettingsManager.Site.MailTo, string.Empty,
                  vm.Subject, emailBody, emailAccount.Smtpserver, emailAccount.Email, SettingsManager.Site.SiteName,
                  emailAccount.UserName, EncryptionHelper.Decrypt(emailAccount.Password), (int)emailAccount.Port, emailAccount.EnableSsl);


                AR.SetSuccess(Messages.EmailSentSuccess);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }
            catch (Exception er)
            {
                AR.Setfailure(er.Message);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

        }

        public string ReplaceTemplate(string body)
        {
            body = body.Replace("{SiteName}", SettingsManager.Site.SiteName);
            body = body.Replace("{SiteURL}", SettingsManager.Site.SiteDomainName);

            return body;
        }
    }
}

SiteWeb/Controllers/DownloadController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TZGCMS.Data.Entity.Doc;
using TZGCMS.Data.Enums;
using TZGCMS.Infrastructure.Configs;
using TZGCMS.Infrastructure.Logging;
using TZGCMS.Model.Front.ViewModel.Doc;
using TZGCMS.Service.Doc;
using TZGCMS.Service.PageMetas;

namespace TZGCMS.SiteWeb.Controllers
{
    public class DownloadController : BaseController
    {

        // GET: Download
        //public ActionResult Index(int? page, int? cateId)
        //{
        //    var vm = new DocumentListFVM
        //    {
        //        CateId = cateId??0,
        //        PageSize = SettingsManager.Doc.PageSize,
        //        PageIndex = page??1,
        //        Categories = _categoryService.GetAll().Where(d=>d.Active).OrderByDescending(d=>d.Importance)
        //    };
        //    int totalCount;
        //    var list = _docService.GetActivePagedElements(vm.PageIndex - 1, vm.PageSize, string.Empty, vm.CateId, out totalCount);
        //    //var categoryVMList = _mapper.Map<List<Article>, List<ArticleVM>>(goodslist);
        //    vm.TotalCount = totalCount;

        //    vm.Documents = new StaticPagedList<Document>(list, vm.PageIndex, vm.PageSize, vm.TotalCount);
        //    var url = Request.RawUrl;
        //    ViewBag.PageMeta = _pageMetaService.GetPageMeta(ModelType.MENU, url);
        //    return View(vm);
        //}
        public ActionResult NewDocument()
        {
          
            var doc =  _db.Documents.OrderByDescending(d=>d.Importance)
                .ThenByDescending(d=>d.Id).FirstOrDefault(d=>d.Active);

            return PartialView("_NewDocument", doc);

        }
        public ActionResult BotDocument()
        {

            var doc = _db.Documents.OrderByDescending(d => d.Importance)
                .ThenByDescending(d => d.Id).FirstOrDefault(d => d.Active);

            return PartialView("_BotDocument", doc);

        }
        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document doc = await _db.Documents.FindAsync(id);
            if (doc == null)
            {
                return HttpNotFound();
            }


            doc.DownloadCount++;
            _db.Entry(doc).State = EntityState.Modified;
            await _db.SaveChangesAsync();


            try
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(Server.MapPath(doc.FilePath));
                string fileName = doc.Title + "." + doc.Extension;
                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }
            catch (Exception er)
            {
                TempData["Error"] = er.Message.ToString();
                return RedirectToAction("ServerError", "Error");
            }

            
        }


    }
}

SiteWeb/Controllers/PagesController.cs
using QNZ.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TZGCMS.Data.Entity;
using TZGCMS.Data.Enums;
using TZGCMS.Infrastructure.Cache;
using TZGCMS.SiteWeb.Filters;

namespace TZGCMS.SiteWeb.Controllers.Pages
{
    public class PagesController : Controller
    {

        private readonly IQNZDbContext _db;
        private readonly ICacheService _cacheService;
        public PagesController(ICacheService cacheService, IQNZDbContext db)
        {
            _cacheService = cacheService;
            _db = db;
        }
        // GET: Pages     
        [SIGActionFilter]
        public ActionResult Index(string seoName)
        {
            var page = _db.Pages.FirstOrDefault(d => d.Active && d.SeoName == seoName);
            if (page == null)
                return HttpNotFound();

            ViewBag.PageMeta = _db.PageMetas.FirstOrDefault(d=>d.ModelType == (short)ModelType.PAGE && d.ObjectId == page.Id.ToString());
            return View(page);
        }

        public ActionResult Paragraph(string seoName)
        {
            var page = _db.Pages.FirstOrDefault(d => d.Active && d.SeoName == seoName);
     
            return PartialView("_Paragraph", page);
        }

    }
}

SiteWeb/Views/Contact/Index.cshtml
@model IEnumerable<OutletVM>
@{

    QNZ.Data.PageMeta pm = (QNZ.Data.PageMeta)ViewBag.PageMeta;
    ViewBag.Title = pm != null ? pm.Title : "联系我们";


}
@section header{
    @if (pm != null)
    {
        <meta name="description" content="@pm.Description" />
        <meta name="keywords" content="@pm.Keyword" />
    }
    <link href="~/Plugins/toastr/toastr.min.css" rel="stylesheet" />

}



<div class="page-contact">
    <section class="s2  wow slideInUp" id="map_canvas">&nbsp;</section>
    <section class="s1">
        <div class="container">
            <div class="title-section">
                <h2 class="wow slideInUp">@SettingsManager.Company.CompanyName</h2>
                <p class="wow slideInUp">
                    地址：@SettingsManager.Company.Address 
                </p>
            </div>
            <div class="outlets">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-xl-6">
                            <div class="outlet wow slideInUp">
                                <div class="row align-items-center">
                                    <div class="col-md-auto">
                                        <img src="@item.Thumbnail" alt="@item.Name" />
                                    </div>
                                    <div class="col-md">
                                        <div class="txt">
                                            <h3>@item.Name</h3>
                                            <dl>
                                                <dd>地址：@item.Address</dd>
                                                <dd>联系人：@item.ContactMan @item.Phone</dd>
                                            </dl>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="moreoutlet wow slideInUp">
                <h4>更多店</h4>
                <p>郑州，西安，长沙、杭州、东莞、重庆、<br />成都等正在筹备中</p>
            </div>
        </div>
    </section>

</div>


@section footer{

    <script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.15&key=05f5bda4fee10ca031971be07a04911b"></script>
    <script>
          $(document).ready(function () {
             $("#progress").height("100%");         
            $("#overly").fadeOut(1000);

            if (Modernizr.mq('(max-width: 991px)')) {
                $("#site-header").css({ "top": "0" });
                setTimeout(function () {
                    $("#progress").css({ "left": "-65px" });
                }, 300);

            } else {
                $("#site-header").css({ "left": "0" });
            }

          });

        var map = new AMap.Map('map_canvas', {
            resizeEnable: true,
            zoom: 17,
            center: [113.931679, 22.588017],
            mapStyle: "amap://styles/whitesmoke"
        });

        // 构造点标记
        var marker = new AMap.Marker({
            icon: "/content/img/marker.png",
            position: [113.931679, 22.588017]
        });

        // 单独将点标记添加到地图上
        map.add(marker);

      
    </script>
}

SiteWeb/Views/Contact/__Index.cshtml
@model EmailIM
@{

    PageMeta pm = (PageMeta)ViewBag.PageMeta;
    ViewBag.Title = pm != null ? pm.Title : "联系我们";

    ViewBag.HeaderClass = "header-white";
}
@section header{
    @if (pm != null)
    {
        <meta name="description" content="@pm.Description" />
        <meta name="keywords" content="@pm.Keyword" />
    }
    <link href="~/Plugins/toastr/toastr.min.css" rel="stylesheet" />
    <style>
        #success-msg-container,
        #fail-msg-container {
            display: none;
        }
    </style>

}

@Html.Action("SingleAd", "AD", new { code = "A1005" })

<div class="page page-contact">
    @Html.Action("Paragraph", "Pages", new { seoName = "contact" })

    <section class="s3" id="s3">
        <div class="container">
            <h3>
                我有此类服务需求
            </h3>
            <p>请简要描述您需要的服务类型，我们的服务团队将第一时间给你取的联系。</p>
            <div class="contact-form">
                @using (Ajax.BeginForm("SendEmail", null, new AjaxOptions
                {

                    HttpMethod = "POST",
                    OnBegin = "onBeginSave",
                    OnComplete = "onCompleteSave",
                    OnSuccess = "updateSuccess"

                }, new { role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)


                    <div class="form-group">

                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "公司名称" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>

                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "邮箱" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = "电话" })
                        @Html.ValidationMessageFor(model => model.Phone)
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(m => m.Body, new { @class = "form-control", placeholder = "留言", rows = "8" })
                        @Html.ValidationMessageFor(model => model.Body)

                    </div>
                    <div class="form-group">
                        <div class="row no-gutters">
                            <div class="col">
                                @Html.TextBoxFor(m => m.CaptchaText, new { @class = "form-control", placeholder = "验证码" })
                                @Html.ValidationMessageFor(model => model.CaptchaText)
                            </div>
                            <div class="col-auto"><img src='@Url.Action("ShowCaptchaImage","Account")' alt="验证码" /></div>
                        </div>

                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn-send">提 交</button>
                    </div>

                }
            </div>
            @Html.Action("NewDocument", "Download")


        </div>
    </section>
</div>




@section footer{
    @Scripts.Render("~/bundles/jqueryvalAjax")
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <script src="~/Plugins/blockUI/jquery.blockUI.min.js"></script>

    <script>

    function onBeginSave() {
       $.blockUI({ message: '<p>提交中...</p>' });
    }
    function onCompleteSave() {
       $.unblockUI();
    }

    function updateSuccess(data) {
      
      //  Common.ShowBox(data.Status, data.Message, title);

        switch (data.Status) {
            case 1:
                toastr.success(data.Message)
                $(".downloads a").removeClass("isDisabled");
                break;
            case 2:
                toastr.error(data.Message)
                break;
            case 3:
                toastr.info(data.Message)
                break;
            case 4:
                toastr.warning(data.Message)
        }
    }

    </script>
    <script src="http://api.map.baidu.com/api?v=2.0&ak=G7h0sKsr60IFU3OrHRmKTRzD"></script>
    <script>
        // 百度地图API功能
        var map = new BMap.Map("map_canvas");


        map.addControl(new BMap.NavigationControl());
        map.enableScrollWheelZoom();    //启用滚轮放大缩小，默认禁用
        map.enableContinuousZoom();    //启用地图惯性拖拽，默认禁用

        map.centerAndZoom(new BMap.Point(113.007022,23.15476), 16);
        var point = new BMap.Point(113.007022,23.15476);

        // var myIcon = new BMap.Icon("/Themes/fengneng/Content/img/marker.png", new BMap.Size(132, 132));
        //  var marker1 = new BMap.Marker(point, { icon: myIcon });  // 创建标注
        var marker1 = new BMap.Marker(point);

        map.addOverlay(marker1);              // 将标注添加到地图中
        // marker1.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
        var sContent =
            "<h4 style='margin:0 0 5px 0;padding:0.2em 0'>佛山市孚瑞美科技有限公司</h4>" +
            "<p>地址：佛山市南海区狮山镇桃园西路狮山罗洞邹边工业区4号 <br/>" +
            "电话：0757-81230272</p>" +
            "</div>";


        //创建信息窗口
        var infoWindow1 = new BMap.InfoWindow(sContent);
        marker1.addEventListener("click", function () { this.openInfoWindow(infoWindow1); });

        // marker1.openInfoWindow(infoWindow1);

    </script>
}