SiteWeb/Areas/Admin/Controllers/LuceneController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using TZGCMS.Infrastructure.Configs;
using TZGCMS.Infrastructure.Helper;
using TZGCMS.Model;
using TZGCMS.Model.Admin.ViewModel;
using TZGCMS.Model.Search;
using TZGCMS.Resources.Admin;
namespace TZGCMS.SiteWeb.Areas.Admin.Controllers
{
    public class LuceneController : BaseController
    {
        private readonly IMapper _mapper;

        public LuceneController(IMapper mapper)
        {
            _mapper = mapper;
        }
        public ActionResult Index(string searchTerm, int? page)
        {
            var vm = new LuceneListVM()
            {
                SearchTerm = searchTerm,            
                PageIndex = (page ?? 1) - 1,
                PageSize = SettingsManager.Lucene.PageSize
            };

            // create default Lucene search index directory
            if (!Directory.Exists(LuceneHelper._luceneDir))
                Directory.CreateDirectory(LuceneHelper._luceneDir);

            int totalCount = 0;
            // perform Lucene search
            List<SearchData> _searchResults = LuceneHelper.SearchDefault(vm.PageIndex, vm.PageSize, out totalCount, searchTerm).ToList();
                                

            // setup and return view model
            var search_field_list = new
                List<SelectedList> {
                                         new SelectedList {Text = "--所有字段--", Value = ""},
                                         new SelectedList {Text = "标题", Value = "Name"},
                                         new SelectedList {Text = "网址", Value = "Name"},
                                         new SelectedList {Text = "内容", Value = "Description"}

                                     };


            vm.TotalCount = totalCount;
            vm.SearchIndexData = new StaticPagedList<SearchData>(_searchResults, vm.PageIndex + 1, vm.PageSize, vm.TotalCount); ;
            vm.SearchFieldList = search_field_list;

            ViewBag.PageSizes = new SelectList(Site.PageSizes());

            return View(vm);

        }

        [HttpPost]
        public JsonResult PageSizeSet(int pageSize)
        {
            try
            {
                var xmlFile = Server.MapPath("~/Config/LuceneSettings.config");
                XDocument doc = XDocument.Load(xmlFile);

                var item = doc.Descendants("Settings").FirstOrDefault();
                item.Element("PageSize").SetValue(pageSize);
                doc.Save(xmlFile);

                return Json(AR, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                AR.Setfailure(ex.Message);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }
        }

    


        [HttpGet]
        public PartialViewResult AddToIndex()
        {

            return PartialView("_AddToIndex");
        }

        [HttpPost]
        public ActionResult AddToIndex(SearchDataIM sampleData)
        {
            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            var im = _mapper.Map<SearchData>(sampleData);
            LuceneHelper.AddUpdateLuceneIndex(im);

            AR.SetSuccess(String.Format(Messages.AlertCreateSuccess, "索引目录"));
            return Json(AR, JsonRequestBehavior.DenyGet);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ClearIndex()
        {
            if (LuceneHelper.ClearLuceneIndex())
            {
                AR.SetSuccess(String.Format(Messages.AlertDeleteSuccess, "索引"));
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            else
            {
                AR.Setfailure("索引被锁，不能被清除，迟点再试！");
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ClearIndexRecord(string id)
        {
            try
            {
                LuceneHelper.ClearLuceneIndexRecord(id);

                AR.SetSuccess(String.Format(Messages.AlertDeleteSuccess, "索引"));
                return Json(AR, JsonRequestBehavior.DenyGet);
            }
            catch (Exception er)
            {
                AR.Setfailure(er.Message);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

        }

      
    }
}

SiteWeb/Areas/Admin/Views/Lucene/Index.cshtml
@model LuceneListVM

@{
    ViewBag.Title = "全站搜索";
    ViewBag.PageTitle = ViewBag.Title + "_内容";
}

<div class="content_left">
  <span style="color: green;">@TempData["Result"]</span>
  <span style="color: red;">@TempData["ResultFail"]</span>
</div>

@section header{
<link href="~/bower_components/ekko-lightbox/dist/ekko-lightbox.min.css" rel="stylesheet" />
    <link href="~/plugins/SigFinder/SigFinder.min.css" rel="stylesheet" />
    <link href="~/plugins/webuploader/webuploader.css" rel="stylesheet" />
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-8">
                @using (Html.BeginForm("Index", "Lucene", FormMethod.Get, new { @class = "form-inline" }))
                {
                  
                        <div class="form-group">                          
                            @Html.TextBoxFor(m => m.SearchTerm, new { @class = "form-control", autocomplete = "off", placeholder= "关键字" })
                        </div>
                   
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search fa-fw"></i>查找</button>

                        }
                    </div>
            <div class="col-sm-4 text-right">
                @Ajax.RawActionLink("<i class='fa fa-plus fa-fw'></i>添加索引",
                        "AddToIndex", "Lucene",
                        new { },
                        new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "edit-container", OnComplete = "onAjaxComplete", OnSuccess = "OnSuccessLink" },
                        new { @class = "btn btn-primary" })

                <a href="#" data-url="@Url.Action("ClearIndex")" class="btn btn-danger clearIndex"><i class="fa fa-trash-o fa-fw"></i>清空索引</a>
               
            </div>
        </div>
        
       
    </div>


    
    @if (Model.SearchIndexData.Any()) {
      <table class="table table-striped">
        <tr>
          <th>图片</th>
          <th>标题</th>
          <th>网址</th>
            <th>创建日期</th>
          <th>操作</th>
        </tr>
        @foreach (var record in Model.SearchIndexData)
        {
            <tr class="item-container">
                <td>
                    @if (!string.IsNullOrEmpty(record.ImageUrl))
                    {
                       <img src="@string.Format("{0}?width=60&height=30&mode=crop", record.ImageUrl)" alt="@record.Name" />                     
                    }
                </td>
                <td>@record.Name</td>
                <td>@record.Url</td>
                <td>@record.CreatedDate</td>
                <td>
                    <a href="#" data-url="@Url.Action("ClearIndexRecord", new {id = record.Id})" class="btn btn-danger btn-sm delete-item" title="@Buttons.Delete">
                        <i class="fa fa-trash-o fa-fw"></i> @Buttons.Delete
                    </a>
                </td>
            </tr>
        }		
      </table>
    }
    else
    {
        <div class="panel-body">
            <p>没有找到任何索引记录！</p>
        </div>
    }
    <footer class="panel-footer">
        <div class="row">
            <div class="col-sm-7">
                @Html.PagedListPager(Model.SearchIndexData, page => Url.Action("Index", new { page = page }))
            </div>
            <div class="col-sm-5">
                <div class="form-inline text-right">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon3"> 总记录<strong>@Model.TotalCount</strong>条，分页</span>
                        @Html.DropDownListFor(m => Model.PageSize, (SelectList)ViewBag.PageSizes, "分页", new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>


    </footer>

</div>

@Html.Action("PopuFinder", "File")

<div id="edit-container">
</div>

<form id="anti-form" method="post">
    @Html.AntiForgeryToken()
</form>

@section footer {
    @Scripts.Render("~/bundles/jqueryvalWithBootstrap")

<script src="~/bower_components/ekko-lightbox/dist/ekko-lightbox.min.js"></script>
<script src="/Plugins/webuploader/webuploader.min.js"></script>
<script src="/Plugins/SigFinder/FileManager.js"></script>

<script type="text/javascript">

    function SetImageUrl() {
        var fileUrl = $("#fileList .item.active").attr("data-file");
        $('#ImageUrl').val(fileUrl);
        $('#fileManagerModal').modal('hide');
    }

        function OnSuccessLink(data) {
            Common.ShowBox(data.Status, data.Message, "操作")
        }

        function onAjaxComplete() {
            $('#ModalEdit').modal();

            $(document).on("click", "#btnImageUrl", function () {
                $('#fileManagerModal').modal();
                $("#selectImage").unbind('click');
                $("#selectImage").bind("click", function () {
                    SetImageUrl();
                });
            });
        }
        function onBegin() {
            $("#btnSave i").removeClass("fa-save").addClass("fa-spinner fa-spin")
        }
        function onComplete() {
            $("#btnSave i").removeClass("fa-spinner fa-spin").addClass("fa-save")
        }


        function updateSuccess(data) {
            var title = '@ViewBag.PageTitle';
            Common.ShowBoxWithFuncBack(data, title, submitSuccess);
        }

        function submitSuccess(id,htmlData) {
            $('#ModalEdit').modal('hide');
            window.location.reload(true);
        }


        $(document).ready(function () {


            //lightbox events
            $(document).delegate('*[data-toggle="lightbox"]', 'click', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });
	
            $(document).on("change", '#PageSize', function (e) {
                e.preventDefault();

                var url = "@Url.Action("PageSizeSet")", title = "分页设置", pageSize = $(this).val();
                Common.PageSizeSet(url, title, pageSize, setPageSizeFunc);

            });

            function setPageSizeFunc() {
                location.reload();
            }

         //delete
            $(document).on("click", '.delete-item', function (e) {
                e.preventDefault();

                var url = $(this).attr('data-url');
                var that = $(this);
                bootbox.setLocale("zh_CN");
                bootbox.confirm("你确定要删除此项吗？", function (result) {
                    /*DELETE*/
                    if (result) {
                        var title = "@ViewBag.Title";
                        Common.DeleteItem(url, title, that);
                    }

                });

        });


        // create index
        $(document).on("click", '.optimize', function (e) {
            e.preventDefault();
            var url = $(this).attr('data-url');
            var that = $(this);
            bootbox.setLocale("zh_CN");
            bootbox.confirm("你确定要优化索引目录吗？", function (result) {
                if (result) {
                    var title = "优化索引目录";
                    $.post(url, $("#anti-form").serialize(), function (data) {
                        Common.ShowBox(data.Status, data.Message, title);
                    })
                }
            });
        });

        $(document).on("click", '.clearIndex', function (e) {
            e.preventDefault();
            var url = $(this).attr('data-url');
            var that = $(this);
            bootbox.setLocale("zh_CN");
            bootbox.confirm("你确定要清空索引目录吗？", function (result) {
                if (result) {
                    var title = "清空索引目录";
                    $.post(url, $("#anti-form").serialize(), function (data) {
                        Common.ShowBoxWithFunc(data, title, clearIndex);
                    })
                }
            });
        });

        });
        function clearIndex() {
            $(".table").remove();
        }
</script>

}

SiteWeb/Areas/Admin/Views/Lucene/_AddToIndex.cshtml
@model SearchDataIM

@using (Ajax.BeginForm("AddToIndex", "Lucene",
                new AjaxOptions()
                {
                    HttpMethod = "POST",
                    OnBegin = "onBegin",
                    OnComplete = "onComplete",
                    OnSuccess = "updateSuccess",
                    //OnFailure = "handleError",
                    //  UpdateTargetId = "RoleList"

                }, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <!-- 添加菜单 Modal -->
    <div class="modal fade" id="ModalEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加索引</h4>
                </div>
                <div class="modal-body">



                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, new { @class = "col-md-2 control-label" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = Labels.Title })
                                    @Html.ValidationMessageFor(model => model.Name)
                                </div>
                            </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.Url, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Url, new { @class = "form-control", placeholder = Labels.Url })
                            @Html.ValidationMessageFor(model => model.Url)
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = Labels.Description })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            <div class="input-group">
                                @Html.TextBoxFor(model => model.ImageUrl, new { @class = "form-control", placeholder = Labels.ImageURL })
                                <span class="input-group-btn">
                                    <button class="btn btn-default" id="btnImageUrl" type="button">浏览…</button>
                                </span>
                            </div><!-- /input-group -->                          

                            @Html.ValidationMessageFor(model => model.ImageUrl)
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button class="btn btn-primary" type="submit" id="btnSave"><i class="fa fa-save fa-fw"></i>保存</button>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>