SiteWeb/Areas/Admin/Controllers/JobsController.cs
using AutoMapper;
using TZGCMS.SiteWeb.Filters;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;
using TZGCMS.Data.Enums;
using TZGCMS.Infrastructure.Configs;
using TZGCMS.Infrastructure.Helper;
using TZGCMS.Model.Admin.ViewModel;

using TZGCMS.Resources.Admin;
using PagedList;
using TZGCMS.Model;
using QNZ.Data;
using System.Data.Entity;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;

namespace TZGCMS.SiteWeb.Areas.Admin.Controllers
{
    [SIGAuth]
    public class JobsController : QNZBaseController
    {
        private IQNZDbContext _db;
        private IMapper _mapper;
        public JobsController(IMapper mapper, IQNZDbContext db)
        {
            _db = db;
            _mapper = mapper;
        }


        // GET: Admin/Jobs
        public async Task<ActionResult> Index(int? page, string keyword)
        {
            JobListVM pageListVM = await GetElementsAsync(page, keyword);
            ViewBag.PageSizes = new SelectList(Site.PageSizes());
            return View(pageListVM);

        }

        private async Task<JobListVM> GetElementsAsync(int? page, string keyword)
        {
            var vm = new JobListVM()
            {
                Keyword = keyword,
                PageIndex = page ?? 1,
                PageSize = SettingsManager.Job.PageSize
            };
            var query = _db.Jobs.AsQueryable();
            if (!string.IsNullOrEmpty(keyword))
            {
                query = query.Where(d => d.Post.Contains(keyword) || d.Description.Contains(keyword));
            }

            var pagelist = await query.OrderByDescending(d => d.Importance).Skip((vm.PageIndex - 1) * vm.PageSize).Take(vm.PageSize).ProjectTo<JobVM>().ToListAsync();
                //_jobServices.GetJobdElements(pageListVM.PageIndex - 1, pageListVM.PageSize, pageListVM.Keyword, out totalCount);

            vm.TotalCount = await query.CountAsync();
            vm.Jobs = new StaticPagedList<JobVM>(pagelist, vm.PageIndex, vm.PageSize, vm.TotalCount); ;
            return vm;
        }
        [HttpPost]
        public JsonResult JobSizeSet(int pageSize)
        {
            try
            {
                var xmlFile = Server.MapPath("~/Config/JobSettings.config");
                XDocument doc = XDocument.Load(xmlFile);

                var item = doc.Descendants("Settings").FirstOrDefault();
                item.Element("JobSize").SetValue(pageSize);
                doc.Save(xmlFile);

                return Json(AR, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                AR.Setfailure(ex.Message);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }
        }


        //// GET: Admin/Jobs/Create
        //public ActionResult Create()
        //{
        //    JobIM job = new JobIM()
        //    {
        //        Active = true
        //    };
        //    return PartialView("_Create", job);
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[ValidateInput(false)]
        //public async System.Threading.Tasks.Task<JsonResult> Create(JobIM job)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        AR.Setfailure(GetModelErrorMessage());
        //        return Json(AR, JsonRequestBehavior.DenyGet);
        //    }

        //    //try
        //    //{
        //        var newJob = _mapper.Map<JobIM, Job>(job);              

        //        var result = _db.Jobs.Add(newJob);
        //    _db.SaveChanges();

        //        if (result!=null)
        //        {
        //            var pageMeta = new PageMetaSet()
        //            {
        //                ObjectId = result.ToString(),
        //                Title = string.IsNullOrEmpty(job.SEOTitle) ? job.Post : job.SEOTitle,
        //                Keyword = string.IsNullOrEmpty(job.Keywords) ? job.Post : job.Keywords.Replace('，', ','),
        //                Description = job.SEODescription,
        //                ModelType = (short)ModelType.JOB
        //            };
        //          //  _pageMetaServices.Create(pageMeta);
        //            _db.PageMetas.Add(pageMeta);
        //            _db.SaveChanges();
        //        }

        //        int pageSize = SettingsManager.Job.PageSize;
        //        var list = await _db.Jobs.OrderByDescending(d => d.Importance).Take(pageSize).ProjectTo<JobVM>().ToListAsync();
        //    //_jobServices.GetJobdElements(0, pageSize, string.Empty, out count);

        //    AR.Data = RenderPartialViewToString("_JobList", list);

        //        AR.SetSuccess(String.Format(Messages.AlertCreateSuccess, EntityNames.Job));
        //        return Json(AR, JsonRequestBehavior.DenyGet);
        //    //}
        //    //catch (Exception er)
        //    //{
        //    //    AR.Setfailure(er.Message);
        //    //    return Json(AR, JsonRequestBehavior.DenyGet);
        //    //}

        //}

        // GET: Admin/Jobs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {

            var vm = new JobIM
            {
                Active = true,
                Importance = 0
            };

            if (id > 0)
            {
                var vAchi = await _db.Jobs.FindAsync(id);
                if (vAchi == null)
                {
                    AR.Setfailure(Messages.HttpNotFound);
                    return Json(AR, JsonRequestBehavior.AllowGet);
                }

                vm = _mapper.Map<Job, JobIM>(vAchi);

                //var pageMeta = await _db.PageMetas.FirstOrDefaultAsync(d => d.ModelType == (short)ModelType.JOB && d.ObjectId == editJob.Id.ToString());
                //    //_pageMetaServices.GetPageMeta(ModelType.JOB, editJob.Id.ToString());
                //if (pageMeta != null)
                //{
                //    editJob.SEOTitle = pageMeta.Title;
                //    editJob.Keywords = pageMeta.Keyword;
                //    editJob.SEODescription = pageMeta.Description;
                //}
            }

            var dictionaries = await _db.Dictionaries.Where(d=>d.TypeId==2).OrderByDescending(m => m.Importance).ToListAsync();
            ViewBag.Categories = new SelectList(dictionaries, "Title", "Title");

            return View(vm);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(JobIM vm)
        {
            if (!ModelState.IsValid)
            {
                AR.Setfailure(GetModelErrorMessage());
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            try
            {
                //    var pageMeta = await _db.PageMetas.FirstOrDefaultAsync(d => d.ModelType == (short)ModelType.JOB && d.ObjectId == editJob.Id.ToString());
                //        //_pageMetaServices.GetPageMeta(ModelType.PAGE, editJob.Id.ToString());
                //    pageMeta = pageMeta ?? new PageMetaSet();

                //    pageMeta.ObjectId = page.Id.ToString();
                //    pageMeta.Title = string.IsNullOrEmpty(page.SEOTitle) ? page.Post : page.SEOTitle;
                //    pageMeta.Keyword = string.IsNullOrEmpty(page.Keywords) ? page.Post : page.Keywords.Replace('，', ',');
                //    pageMeta.Description = page.SEODescription;
                //    pageMeta.ModelType = (short)ModelType.JOB;

                if (vm.Id > 0)
                {
                    var job = await _db.Jobs.FindAsync(vm.Id);

                    job = _mapper.Map(vm, job);
                    job.UpdatedBy = Site.CurrentUserName;
                    job.UpdatedDate = DateTime.Now;
                    _db.Entry(job).State = EntityState.Modified;
                    //_db.Entry(pageMeta).State = EntityState.Modified;

                    await _db.SaveChangesAsync();



                    AR.SetSuccess(String.Format(Messages.AlertUpdateSuccess, EntityNames.Job));
                    return Json(AR, JsonRequestBehavior.DenyGet);
                }
                else
                {
                    var newJob = _mapper.Map<JobIM, Job>(vm);
                    newJob.CreatedBy = Site.CurrentUserName;
                    newJob.CreatedDate = DateTime.Now;
                    _db.Jobs.Add(newJob);
                    await _db.SaveChangesAsync();

                    //_db.PageMetas.Add(pageMeta);
                    //await _db.SaveChangesAsync();

                    AR.SetSuccess(String.Format(Messages.AlertCreateSuccess, EntityNames.Job));
                    return Json(AR, JsonRequestBehavior.DenyGet);

                }



            }
            catch (Exception er)
            {
                AR.Setfailure(er.Message);
                return Json(AR, JsonRequestBehavior.DenyGet);
            }

            //if (!ModelState.IsValid)
            //{
            //    AR.Setfailure(GetModelErrorMessage());
            //    return Json(AR, JsonRequestBehavior.DenyGet);
            //}

            //try
            //{
            //    var old = await _db.Jobs.FindAsync(page.Id);
            //    var editJob = _mapper.Map(page, old);

            //    _db.Entry(editJob).State = EntityState.Modified;
            //    await _db.SaveChangesAsync();
            //    //  _jobServices.Update(editJob);

            //    var pageMeta = await _db.PageMetas.FirstOrDefaultAsync(d => d.ModelType == (short)ModelType.JOB && d.ObjectId == editJob.Id.ToString());
            //        //_pageMetaServices.GetPageMeta(ModelType.PAGE, editJob.Id.ToString());
            //    pageMeta = pageMeta ?? new PageMetaSet();

            //    pageMeta.ObjectId = page.Id.ToString();
            //    pageMeta.Title = string.IsNullOrEmpty(page.SEOTitle) ? page.Post : page.SEOTitle;
            //    pageMeta.Keyword = string.IsNullOrEmpty(page.Keywords) ? page.Post : page.Keywords.Replace('，', ',');

SiteWeb/Areas/Admin/Views/Jobs/Edit.cshtml
@model JobIM
@{

    Layout = "~/Areas/Admin/Views/Shared/Layouts/_Layout2019.cshtml";
    ViewBag.Title = "编辑" + EntityNames.Laboratory;
    ViewBag.PageTitle = ViewBag.Title + "_内容";
}


@section Header{

    <link href="~/Plugins/datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />
}


@using (Ajax.BeginForm("Edit", null, new AjaxOptions
{

    HttpMethod = "POST",
    OnBegin = "onBeginSave",
    OnComplete = "onCompleteSave",
    OnSuccess = "updateSuccess"

}, new { @class = "form-horizontal", role = "form" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)


    <div class="card">
        <header class="card-header">
            <span class="glyphicon glyphicon-edit"></span> @ViewBag.Title
        </header>

        <section class="card-body">
            <div class="row">
                <div class="col-md">
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Post, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Post, new { @class = "form-control", placeholder = Labels.Post })
                            @Html.ValidationMessageFor(model => model.Post)
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Category, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Category, (SelectList)ViewBag.Categories, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Category)
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Address, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Address)
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Description, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                    </div>



                    <div class="form-group row">
                        @Html.LabelFor(model => model.Quantity, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control", placeholder = Labels.Quantity })
                            @Html.ValidationMessageFor(model => model.Quantity)
                        </div>
                    </div>


                    <div class="form-group row">
                        @Html.LabelFor(model => model.Importance, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Importance, new { @class = "form-control", placeholder = Labels.Importance })
                            @Html.ValidationMessageFor(model => model.Importance)
                        </div>
                    </div>


                    <div class="form-group row">
                        <div class="col-md-2">激活</div>
                        <div class="col-md-10">
                            <div class="form-check">
                                @Html.CheckBoxFor(model => model.Active, new { @class = "form-check-input" })

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-auto">
                   
                </div>
            </div>
        
  

        </section>
        <footer class="card-footer text-center">
            <button type="submit" class="btn btn-primary" id="btnSave"><i class="fa fa-save fa-fw"></i>  @Buttons.Update </button>
            <a href="@Url.Action("Index")" class="btn btn-secondary"><span class="fa fa-chevron-left fa-fw"></span> @Buttons.Back</a>
        </footer>

    </div>
}




@section Footer {
    @Scripts.Render("~/bundles/jqueryvalWithBootstrap")
    <script src="~/Plugins/tinymce5/tinymce.min.js"></script>
    <script src="~/scripts/lib/moment/moment-with-locales.min.js"></script>
    <script src="~/Plugins/datetimepicker/jquery.datetimepicker.full.min.js"></script>
    <script src="~/Plugins/holderjs/holder.min.js"></script>
    <script>


        function SetThumbnail(fileUrl) {
            $("#iLogo").attr("src", fileUrl);
            $('#Thumbnail').val(fileUrl);
        }


        function onBeginSave() {
            $("#btnSave i").removeClass("fa-save").addClass("fa-spinner fa-spin");
        }
        function onCompleteSave() {
            $("#btnSave i").removeClass("fa-spinner fa-spin").addClass("fa-save");
        }

        function updateSuccess(data) {
            var title = '@ViewBag.Title';
            Common.ShowBox(data.Status, data.Message, title);
        }


        tinymce.init({
            selector: '#Description',  // change this value according to your HTML
            height: 400,
            language: 'zh_CN',

            convert_urls: false,
            extended_valid_elements: 'span',
            image_advtab: true,

            //picture manager
            file_picker_callback: singleEelFinder.elFinderBrowser,
            images_upload_handler: singleEelFinder.ImagesUploadHandler,
            plugins: 'print preview code importcss  searchreplace autolink autosave save directionality  visualblocks visualchars fullscreen image link media  template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists  wordcount   imagetools textpattern noneditable help    charmap   quickbars  emoticons',

              toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment code',
              autosave_ask_before_unload: true,
              autosave_interval: "30s",
              autosave_prefix: "{path}{query}-{id}-",
              autosave_restore_when_empty: false,
                autosave_retention: "2m",

            image_advtab: true,
            importcss_append: true,
            image_caption: true,
            templates: [
                { title: '新表格', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
            { title: '文章样式', description: 'A cure for writers block', content: 'Once upon a time...' },
            { title: '列表样式', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
          ]


        });




        $(function () {

            $("#btnThumbnail").on("click", function() {
                singleEelFinder.selectActionFunction = SetThumbnail;
                singleEelFinder.open();
            });




            $.datetimepicker.setLocale('ch');
            $('#Pubdate').datetimepicker();
        })

    </script>
}

SiteWeb/Areas/Admin/Views/Jobs/Index.cshtml
@model JobListVM
@{
      Layout = "~/Areas/Admin/Views/Shared/Layouts/_Layout2019.cshtml";
    ViewBag.Title = EntityNames.Job;
}

@section Header{

}

    <div class="row mb-3">
        <div class="col-sm">
            @using (Html.BeginForm("Index", "Jobs", FormMethod.Get, new { @class = "form-inline" }))
            {
                <div class="form-group">
                    <label class="sr-only" for="Keyword">关键字</label>
                    @Html.TextBoxFor(model => model.Keyword, new { @class = "form-control mr-sm-2", placeholder = "关键字" })
                </div>
                <button type="submit" class="btn btn-primary"><i class="iconfont icon-search"></i> 查找</button>
            }
        </div>
        <div class="col-sm-auto">
            <a class="btn btn-primary" href="@Url.Action("Edit")"><i class="iconfont icon-edit"></i> @string.Format("{0}{1}", Buttons.Add, ViewBag.Title)</a>
        </div>

    </div>

    <div class="table-responsive">
        <table class="table table-hover table-striped table-vmiddle">
            <thead>
                <tr>
                    <th>
                        主题
                    </th>

                    <th>
                        类型
                    </th>
                    <th>
                        工作地点
                    </th>
                    <th>创建日期</th>
                    <th>
                        激活？
                    </th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody id="tbList">
                @foreach (var item in Model.Jobs)
                {
                    Html.RenderPartial("_JobItem", item);
                }
            </tbody>

        </table>
    </div>

    <div class="container-fluid pt-3" style="background-color: #fff;">
        <div class="row">
            <div class="col-sm">
                @Html.PagedListPager(Model.Jobs, page => Url.Action("Index", new { page = page, keyword = Model.Keyword }))
            </div>
            <div class="col-md-auto">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">总记录<strong>@Model.TotalCount</strong>条，分页</span>
                    </div>
                    @Html.DropDownListFor(m => Model.PageSize, (SelectList)ViewBag.PageSizes, "分页", new { @class = "custom-select" })
                </div>

            </div>
        
        </div>
        </div>



        <div id="edit-container">
        </div>

        <form id="anti-form" method="post">
            @Html.AntiForgeryToken()
        </form>

        @section Footer {
            @Scripts.Render("~/bundles/jqueryvalWithBootstrap")
            <script src="~/plugins/tinymce/tinymce.min.js"></script>
            <script src="~/plugins/tinymce/langs/zh_CN.js"></script>
            <script src="~/Plugins/ace/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>

            <script>


        function OnSuccessLink(data) {
            Common.ShowBox(data.Status, data.Message, "操作")
        }

        function onAjaxComplete() {
            $('#ModalEdit').modal();



            tinymce.init({
                selector: '#Description',  // change this value according to your HTML
                height: 250,
                language: 'zh_CN',
                theme: 'modern',
                convert_urls: false,
                extended_valid_elements: 'main[class|id]',
                custom_elements: 'main',
                verify_html: false,
                plugins: [
                  'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                  'searchreplace wordcount visualblocks visualchars code fullscreen',
                  'insertdatetime media nonbreaking save table contextmenu directionality',
                  'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
                ],
                toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image print preview media | forecolor backcolor emoticons | codesample',
                image_advtab: true,
                templates: [
                  { title: 'Test template 1', content: 'Test 1' },
                  { title: 'Test template 2', content: 'Test 2' }
                ],
                //picture manager
                file_browser_callback: callSigFinder,
                templates: [
            { title: 'Some title 1', description: 'Some desc 1', content: 'My content' },
            { title: 'Some title 2', description: 'Some desc 2', url: 'development.html' }
                ]

            });
            function callSigFinder(field_name, url, type, win) {
                var roxyFileman = '@Url.Action("FinderForTinyMCE","File",new { area="Admin"})';
                tinyMCE.activeEditor.windowManager.open({
                    file: roxyFileman,
                    title: 'SigFinder',
                    width: 850,
                    height: 655,
                    resizable: "yes",
                    plugins: "media",
                    inline: "yes",
                    close_previous: "no"
                }, { window: win, input: field_name });
                return false;

            }
        }
        function onBegin() {
            $("#btnSave i").removeClass("fa-save").addClass("fa-spinner fa-spin")
        }
        function onComplete() {
            $("#btnSave i").removeClass("fa-spinner fa-spin").addClass("fa-save")
        }


         function updateSuccess(data) {
            var title = '@ViewBag.PageTitle';
            Common.ShowBoxWithFuncBack(data, title, submitSuccess);
        }

        function submitSuccess(id,htmlData) {
            $('#ModalEdit').modal('hide');

            if(id>0){
                var cid = "container" + id;
                $("#" + cid).replaceWith(htmlData);
            }
            else {
                $("#tbList").html(htmlData);

            }
        }

        $(function () {
            //解决弹窗里tinymce 里的弹窗编辑失效问题。
            $(document).on('focusin', function (e) {
                if ($(e.target).closest(".mce-window").length) {
                    e.stopImmediatePropagation();
                }
            });

            $(document).on('hidden.bs.modal', '#ModalEdit', function (e) {
                tinymce.remove();
            })

            //pagging set
            $(document).on("change", '#PageSize', function (e) {
                e.preventDefault();

                var url = "@Url.Action("PageSizeSet")", title = "分页设置", pageSize = $(this).val();
                Common.PageSizeSet(url, title, pageSize, setPageSizeFunc);

            });

            function setPageSizeFunc() {
                location.reload();
            }

            //active
            $(document).on("click", '.active-item', function (e) {
                e.preventDefault();

                var url = $(this).attr('data-url'), title = $(this).attr('title'), that = $(this);
                Common.SingleActionWithFuncBack(url, title, that, submitFunc);

            });

            function submitFunc(that,data) {
                var tr = that.closest('.item-container').replaceWith(data);
            }


            //delete
            $(document).on("click", '.delete-item', function (e) {
                e.preventDefault();

                var url = $(this).attr('data-url');
                var that = $(this);
                bootbox.setLocale("zh_CN");
                bootbox.confirm("你确定要删除此项吗？", function (result) {
                    if (result) {
                        /*DELETE*/
                        var title = "@ViewBag.Title";
                        Common.DeleteItem(url, title, that);
                    }
                });
            });

            // create index
            $(document).on("click", '.createIndex', function (e) {
                e.preventDefault();
                var url = $(this).attr('data-url');
                var that = $(this);
                bootbox.setLocale("zh_CN");
                bootbox.confirm("你确定要创建索引目录吗？", function (result) {
                    if (result) {
                        var title = "创建索引目录";
                        $.post(url, function (data) {
                            Common.ShowBox(data.Status, data.Message, title);
                        })
                    }
                });

            });




        });
            </script>

        }

SiteWeb/Areas/Admin/Views/Jobs/_JobItem.cshtml
@model JobVM
<tr class="item-container" id="@string.Format("container{0}",Model.Id)">

    <td>
        @Model.Post
    </td>


    <td>
        @Model.Category
    </td>
    <td>
        @Model.Address
    </td>
    <td>
        @Model.CreatedDate.ToShortDateString()
    </td>
    <td>
        @if (Model.Active)
        {
            <a href="#" data-url="@Url.Action("IsActive", new {id = Model.Id})" class="active-item" title="激活" data-action="锁定">
                <i class="fa fa-check text-success"></i>
            </a>

        }
        else
        {
            <a href="#" data-url="@Url.Action("IsActive", new {id = Model.Id})" class="active-item" title="锁定" data-action="激活">
                <i class="fa fa-remove text-danger"></i>
            </a>
        }
    </td>
    <td>
     
        <a href="@Url.Action("Edit",new {id = Model.Id})" class="btn btn-primary btn-sm" title="@Buttons.Edit"><i class='fa fa-edit fa-fw'></i></a>
        <a href="#" data-url="@Url.Action("Delete", new {id = Model.Id})" class="btn btn-danger btn-sm delete-item" title="@Buttons.Delete">
            <i class="fa fa-trash-o fa-fw"></i>
        </a>
    </td>
</tr>

SiteWeb/Areas/Admin/Views/Jobs/_JobList.cshtml
@model IEnumerable<TZGCMS.Data.Entity.Job>
@foreach (var item in Model)
{
    Html.RenderPartial("_JobItem", item);
}